apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: wishmart-ml-tls
spec:
  secretName: wishmart-ml
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wishmart.ml
  dnsNames:
    - wishmart.ml
    - www.wishmart.ml
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - wishmart.ml
          - www.wishmart.ml
